repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: ["--fix", "soundconverter", "bin/soundconverter.in"]
    -   id: ruff-format
        args: ["--check", "soundconverter", "bin/soundconverter.in"]
